---
all:
  hosts:
    minipc:
      ansible_host: 192.168.178.20
      ansible_user: philipp
      ansible_ssh_private_key_file: ~/.ssh/MiniPC
      ansible_port: 1461
      ansible_sudo_pass: "{{ vault_minipc_passwd }}"
